apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeappdep
  name: nodeappdep
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30007
  selector:
    app: nodeappdep
  type: NodePort
